# Generated by Django 3.1.3 on 2021-03-07 15:36

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210222_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
