# Generated by Django 3.1.3 on 2021-03-08 08:13

from django.db import migrations, models
import django_summernote.fields
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210307_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default=notes.models.title_default, max_length=50),
        ),
    ]
